// automatically generated by the FlatBuffers compiler, do not modify

/**
 * @const
 * @namespace
 */
var pkNX = pkNX || {};

/**
 * @const
 * @namespace
 */
pkNX.Structures = pkNX.Structures || {};

/**
 * @constructor
 */
pkNX.Structures.NestHoleDistributionEncounter8Archive = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {pkNX.Structures.NestHoleDistributionEncounter8Archive}
 */
pkNX.Structures.NestHoleDistributionEncounter8Archive.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {pkNX.Structures.NestHoleDistributionEncounter8Archive=} obj
 * @returns {pkNX.Structures.NestHoleDistributionEncounter8Archive}
 */
pkNX.Structures.NestHoleDistributionEncounter8Archive.getRootAsNestHoleDistributionEncounter8Archive = function(bb, obj) {
  return (obj || new pkNX.Structures.NestHoleDistributionEncounter8Archive).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {pkNX.Structures.NestHoleDistributionEncounter8Archive=} obj
 * @returns {pkNX.Structures.NestHoleDistributionEncounter8Archive}
 */
pkNX.Structures.NestHoleDistributionEncounter8Archive.getSizePrefixedRootAsNestHoleDistributionEncounter8Archive = function(bb, obj) {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new pkNX.Structures.NestHoleDistributionEncounter8Archive).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {number} index
 * @param {pkNX.Structures.NestHoleDistributionEncounter8Table=} obj
 * @returns {pkNX.Structures.NestHoleDistributionEncounter8Table}
 */
pkNX.Structures.NestHoleDistributionEncounter8Archive.prototype.Tables = function(index, obj) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? (obj || new pkNX.Structures.NestHoleDistributionEncounter8Table).__init(this.bb.__indirect(this.bb.__vector(this.bb_pos + offset) + index * 4), this.bb) : null;
};

/**
 * @returns {number}
 */
pkNX.Structures.NestHoleDistributionEncounter8Archive.prototype.TablesLength = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Builder} builder
 */
pkNX.Structures.NestHoleDistributionEncounter8Archive.startNestHoleDistributionEncounter8Archive = function(builder) {
  builder.startObject(1);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} TablesOffset
 */
pkNX.Structures.NestHoleDistributionEncounter8Archive.addTables = function(builder, TablesOffset) {
  builder.addFieldOffset(0, TablesOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {Array.<flatbuffers.Offset>} data
 * @returns {flatbuffers.Offset}
 */
pkNX.Structures.NestHoleDistributionEncounter8Archive.createTablesVector = function(builder, data) {
  builder.startVector(4, data.length, 4);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]);
  }
  return builder.endVector();
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
pkNX.Structures.NestHoleDistributionEncounter8Archive.startTablesVector = function(builder, numElems) {
  builder.startVector(4, numElems, 4);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
pkNX.Structures.NestHoleDistributionEncounter8Archive.endNestHoleDistributionEncounter8Archive = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} offset
 */
pkNX.Structures.NestHoleDistributionEncounter8Archive.finishNestHoleDistributionEncounter8ArchiveBuffer = function(builder, offset) {
  builder.finish(offset);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} offset
 */
pkNX.Structures.NestHoleDistributionEncounter8Archive.finishSizePrefixedNestHoleDistributionEncounter8ArchiveBuffer = function(builder, offset) {
  builder.finish(offset, undefined, true);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} TablesOffset
 * @returns {flatbuffers.Offset}
 */
pkNX.Structures.NestHoleDistributionEncounter8Archive.createNestHoleDistributionEncounter8Archive = function(builder, TablesOffset) {
  pkNX.Structures.NestHoleDistributionEncounter8Archive.startNestHoleDistributionEncounter8Archive(builder);
  pkNX.Structures.NestHoleDistributionEncounter8Archive.addTables(builder, TablesOffset);
  return pkNX.Structures.NestHoleDistributionEncounter8Archive.endNestHoleDistributionEncounter8Archive(builder);
}

/**
 * @constructor
 */
pkNX.Structures.NestHoleDistributionEncounter8Table = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {pkNX.Structures.NestHoleDistributionEncounter8Table}
 */
pkNX.Structures.NestHoleDistributionEncounter8Table.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {pkNX.Structures.NestHoleDistributionEncounter8Table=} obj
 * @returns {pkNX.Structures.NestHoleDistributionEncounter8Table}
 */
pkNX.Structures.NestHoleDistributionEncounter8Table.getRootAsNestHoleDistributionEncounter8Table = function(bb, obj) {
  return (obj || new pkNX.Structures.NestHoleDistributionEncounter8Table).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {pkNX.Structures.NestHoleDistributionEncounter8Table=} obj
 * @returns {pkNX.Structures.NestHoleDistributionEncounter8Table}
 */
pkNX.Structures.NestHoleDistributionEncounter8Table.getSizePrefixedRootAsNestHoleDistributionEncounter8Table = function(bb, obj) {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new pkNX.Structures.NestHoleDistributionEncounter8Table).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {flatbuffers.Long}
 */
pkNX.Structures.NestHoleDistributionEncounter8Table.prototype.TableID = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.readUint64(this.bb_pos + offset) : this.bb.createLong(0, 0);
};

/**
 * @returns {number}
 */
pkNX.Structures.NestHoleDistributionEncounter8Table.prototype.GameVersion = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.readUint32(this.bb_pos + offset) : 0;
};

/**
 * @returns {number}
 */
pkNX.Structures.NestHoleDistributionEncounter8Table.prototype.Field02 = function() {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? this.bb.readInt8(this.bb_pos + offset) : 0;
};

/**
 * @returns {number}
 */
pkNX.Structures.NestHoleDistributionEncounter8Table.prototype.Field03 = function() {
  var offset = this.bb.__offset(this.bb_pos, 10);
  return offset ? this.bb.readInt8(this.bb_pos + offset) : 0;
};

/**
 * @param {number} index
 * @param {pkNX.Structures.NestHoleDistributionEncounter8=} obj
 * @returns {pkNX.Structures.NestHoleDistributionEncounter8}
 */
pkNX.Structures.NestHoleDistributionEncounter8Table.prototype.Entries = function(index, obj) {
  var offset = this.bb.__offset(this.bb_pos, 12);
  return offset ? (obj || new pkNX.Structures.NestHoleDistributionEncounter8).__init(this.bb.__indirect(this.bb.__vector(this.bb_pos + offset) + index * 4), this.bb) : null;
};

/**
 * @returns {number}
 */
pkNX.Structures.NestHoleDistributionEncounter8Table.prototype.EntriesLength = function() {
  var offset = this.bb.__offset(this.bb_pos, 12);
  return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Builder} builder
 */
pkNX.Structures.NestHoleDistributionEncounter8Table.startNestHoleDistributionEncounter8Table = function(builder) {
  builder.startObject(5);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Long} TableID
 */
pkNX.Structures.NestHoleDistributionEncounter8Table.addTableID = function(builder, TableID) {
  builder.addFieldInt64(0, TableID, builder.createLong(0, 0));
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} GameVersion
 */
pkNX.Structures.NestHoleDistributionEncounter8Table.addGameVersion = function(builder, GameVersion) {
  builder.addFieldInt32(1, GameVersion, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} Field02
 */
pkNX.Structures.NestHoleDistributionEncounter8Table.addField02 = function(builder, Field02) {
  builder.addFieldInt8(2, Field02, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} Field03
 */
pkNX.Structures.NestHoleDistributionEncounter8Table.addField03 = function(builder, Field03) {
  builder.addFieldInt8(3, Field03, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} EntriesOffset
 */
pkNX.Structures.NestHoleDistributionEncounter8Table.addEntries = function(builder, EntriesOffset) {
  builder.addFieldOffset(4, EntriesOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {Array.<flatbuffers.Offset>} data
 * @returns {flatbuffers.Offset}
 */
pkNX.Structures.NestHoleDistributionEncounter8Table.createEntriesVector = function(builder, data) {
  builder.startVector(4, data.length, 4);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]);
  }
  return builder.endVector();
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
pkNX.Structures.NestHoleDistributionEncounter8Table.startEntriesVector = function(builder, numElems) {
  builder.startVector(4, numElems, 4);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
pkNX.Structures.NestHoleDistributionEncounter8Table.endNestHoleDistributionEncounter8Table = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Long} TableID
 * @param {number} GameVersion
 * @param {number} Field02
 * @param {number} Field03
 * @param {flatbuffers.Offset} EntriesOffset
 * @returns {flatbuffers.Offset}
 */
pkNX.Structures.NestHoleDistributionEncounter8Table.createNestHoleDistributionEncounter8Table = function(builder, TableID, GameVersion, Field02, Field03, EntriesOffset) {
  pkNX.Structures.NestHoleDistributionEncounter8Table.startNestHoleDistributionEncounter8Table(builder);
  pkNX.Structures.NestHoleDistributionEncounter8Table.addTableID(builder, TableID);
  pkNX.Structures.NestHoleDistributionEncounter8Table.addGameVersion(builder, GameVersion);
  pkNX.Structures.NestHoleDistributionEncounter8Table.addField02(builder, Field02);
  pkNX.Structures.NestHoleDistributionEncounter8Table.addField03(builder, Field03);
  pkNX.Structures.NestHoleDistributionEncounter8Table.addEntries(builder, EntriesOffset);
  return pkNX.Structures.NestHoleDistributionEncounter8Table.endNestHoleDistributionEncounter8Table(builder);
}

/**
 * @constructor
 */
pkNX.Structures.NestHoleDistributionEncounter8 = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {pkNX.Structures.NestHoleDistributionEncounter8}
 */
pkNX.Structures.NestHoleDistributionEncounter8.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {pkNX.Structures.NestHoleDistributionEncounter8=} obj
 * @returns {pkNX.Structures.NestHoleDistributionEncounter8}
 */
pkNX.Structures.NestHoleDistributionEncounter8.getRootAsNestHoleDistributionEncounter8 = function(bb, obj) {
  return (obj || new pkNX.Structures.NestHoleDistributionEncounter8).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {pkNX.Structures.NestHoleDistributionEncounter8=} obj
 * @returns {pkNX.Structures.NestHoleDistributionEncounter8}
 */
pkNX.Structures.NestHoleDistributionEncounter8.getSizePrefixedRootAsNestHoleDistributionEncounter8 = function(bb, obj) {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new pkNX.Structures.NestHoleDistributionEncounter8).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {number}
 */
pkNX.Structures.NestHoleDistributionEncounter8.prototype.EntryIndex = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.readUint32(this.bb_pos + offset) : 0;
};

/**
 * @returns {number}
 */
pkNX.Structures.NestHoleDistributionEncounter8.prototype.Species = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.readUint32(this.bb_pos + offset) : 0;
};

/**
 * @returns {number}
 */
pkNX.Structures.NestHoleDistributionEncounter8.prototype.AltForm = function() {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? this.bb.readUint32(this.bb_pos + offset) : 0;
};

/**
 * @returns {number}
 */
pkNX.Structures.NestHoleDistributionEncounter8.prototype.Level = function() {
  var offset = this.bb.__offset(this.bb_pos, 10);
  return offset ? this.bb.readUint32(this.bb_pos + offset) : 0;
};

/**
 * @returns {number}
 */
pkNX.Structures.NestHoleDistributionEncounter8.prototype.DynamaxLevel = function() {
  var offset = this.bb.__offset(this.bb_pos, 12);
  return offset ? this.bb.readUint16(this.bb_pos + offset) : 0;
};

/**
 * @returns {number}
 */
pkNX.Structures.NestHoleDistributionEncounter8.prototype.Field05 = function() {
  var offset = this.bb.__offset(this.bb_pos, 14);
  return offset ? this.bb.readUint32(this.bb_pos + offset) : 0;
};

/**
 * @returns {number}
 */
pkNX.Structures.NestHoleDistributionEncounter8.prototype.Field06 = function() {
  var offset = this.bb.__offset(this.bb_pos, 16);
  return offset ? this.bb.readUint32(this.bb_pos + offset) : 0;
};

/**
 * @returns {number}
 */
pkNX.Structures.NestHoleDistributionEncounter8.prototype.Field07 = function() {
  var offset = this.bb.__offset(this.bb_pos, 18);
  return offset ? this.bb.readUint32(this.bb_pos + offset) : 0;
};

/**
 * @returns {number}
 */
pkNX.Structures.NestHoleDistributionEncounter8.prototype.Field08 = function() {
  var offset = this.bb.__offset(this.bb_pos, 20);
  return offset ? this.bb.readUint32(this.bb_pos + offset) : 0;
};

/**
 * @returns {number}
 */
pkNX.Structures.NestHoleDistributionEncounter8.prototype.Field09 = function() {
  var offset = this.bb.__offset(this.bb_pos, 22);
  return offset ? this.bb.readUint32(this.bb_pos + offset) : 0;
};

/**
 * @returns {number}
 */
pkNX.Structures.NestHoleDistributionEncounter8.prototype.Field0A = function() {
  var offset = this.bb.__offset(this.bb_pos, 24);
  return offset ? this.bb.readUint32(this.bb_pos + offset) : 0;
};

/**
 * @returns {number}
 */
pkNX.Structures.NestHoleDistributionEncounter8.prototype.Ability = function() {
  var offset = this.bb.__offset(this.bb_pos, 26);
  return offset ? this.bb.readInt8(this.bb_pos + offset) : 0;
};

/**
 * @returns {boolean}
 */
pkNX.Structures.NestHoleDistributionEncounter8.prototype.IsGigantamax = function() {
  var offset = this.bb.__offset(this.bb_pos, 28);
  return offset ? !!this.bb.readInt8(this.bb_pos + offset) : false;
};

/**
 * @returns {flatbuffers.Long}
 */
pkNX.Structures.NestHoleDistributionEncounter8.prototype.DropTableID = function() {
  var offset = this.bb.__offset(this.bb_pos, 30);
  return offset ? this.bb.readUint64(this.bb_pos + offset) : this.bb.createLong(0, 0);
};

/**
 * @returns {flatbuffers.Long}
 */
pkNX.Structures.NestHoleDistributionEncounter8.prototype.BonusTableID = function() {
  var offset = this.bb.__offset(this.bb_pos, 32);
  return offset ? this.bb.readUint64(this.bb_pos + offset) : this.bb.createLong(0, 0);
};

/**
 * @param {number} index
 * @returns {number}
 */
pkNX.Structures.NestHoleDistributionEncounter8.prototype.Probabilities = function(index) {
  var offset = this.bb.__offset(this.bb_pos, 34);
  return offset ? this.bb.readUint32(this.bb.__vector(this.bb_pos + offset) + index * 4) : 0;
};

/**
 * @returns {number}
 */
pkNX.Structures.NestHoleDistributionEncounter8.prototype.ProbabilitiesLength = function() {
  var offset = this.bb.__offset(this.bb_pos, 34);
  return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @returns {Uint32Array}
 */
pkNX.Structures.NestHoleDistributionEncounter8.prototype.ProbabilitiesArray = function() {
  var offset = this.bb.__offset(this.bb_pos, 34);
  return offset ? new Uint32Array(this.bb.bytes().buffer, this.bb.bytes().byteOffset + this.bb.__vector(this.bb_pos + offset), this.bb.__vector_len(this.bb_pos + offset)) : null;
};

/**
 * @returns {number}
 */
pkNX.Structures.NestHoleDistributionEncounter8.prototype.Gender = function() {
  var offset = this.bb.__offset(this.bb_pos, 36);
  return offset ? this.bb.readInt8(this.bb_pos + offset) : 0;
};

/**
 * @returns {number}
 */
pkNX.Structures.NestHoleDistributionEncounter8.prototype.FlawlessIVs = function() {
  var offset = this.bb.__offset(this.bb_pos, 38);
  return offset ? this.bb.readInt8(this.bb_pos + offset) : 0;
};

/**
 * @returns {number}
 */
pkNX.Structures.NestHoleDistributionEncounter8.prototype.Field12 = function() {
  var offset = this.bb.__offset(this.bb_pos, 40);
  return offset ? this.bb.readInt8(this.bb_pos + offset) : 0;
};

/**
 * @returns {number}
 */
pkNX.Structures.NestHoleDistributionEncounter8.prototype.Field13 = function() {
  var offset = this.bb.__offset(this.bb_pos, 42);
  return offset ? this.bb.readInt8(this.bb_pos + offset) : 0;
};

/**
 * @returns {number}
 */
pkNX.Structures.NestHoleDistributionEncounter8.prototype.Field14 = function() {
  var offset = this.bb.__offset(this.bb_pos, 44);
  return offset ? this.bb.readInt8(this.bb_pos + offset) : 0;
};

/**
 * @returns {number}
 */
pkNX.Structures.NestHoleDistributionEncounter8.prototype.Nature = function() {
  var offset = this.bb.__offset(this.bb_pos, 46);
  return offset ? this.bb.readInt8(this.bb_pos + offset) : 0;
};

/**
 * @returns {number}
 */
pkNX.Structures.NestHoleDistributionEncounter8.prototype.Field16 = function() {
  var offset = this.bb.__offset(this.bb_pos, 48);
  return offset ? this.bb.readUint32(this.bb_pos + offset) : 0;
};

/**
 * @returns {number}
 */
pkNX.Structures.NestHoleDistributionEncounter8.prototype.Move0 = function() {
  var offset = this.bb.__offset(this.bb_pos, 50);
  return offset ? this.bb.readUint32(this.bb_pos + offset) : 0;
};

/**
 * @returns {number}
 */
pkNX.Structures.NestHoleDistributionEncounter8.prototype.Move1 = function() {
  var offset = this.bb.__offset(this.bb_pos, 52);
  return offset ? this.bb.readUint32(this.bb_pos + offset) : 0;
};

/**
 * @returns {number}
 */
pkNX.Structures.NestHoleDistributionEncounter8.prototype.Move2 = function() {
  var offset = this.bb.__offset(this.bb_pos, 54);
  return offset ? this.bb.readUint32(this.bb_pos + offset) : 0;
};

/**
 * @returns {number}
 */
pkNX.Structures.NestHoleDistributionEncounter8.prototype.Move3 = function() {
  var offset = this.bb.__offset(this.bb_pos, 56);
  return offset ? this.bb.readUint32(this.bb_pos + offset) : 0;
};

/**
 * @returns {number}
 */
pkNX.Structures.NestHoleDistributionEncounter8.prototype.DynamaxBoost = function() {
  var offset = this.bb.__offset(this.bb_pos, 58);
  return offset ? this.bb.readFloat32(this.bb_pos + offset) : 0.0;
};

/**
 * @returns {number}
 */
pkNX.Structures.NestHoleDistributionEncounter8.prototype.Field1C = function() {
  var offset = this.bb.__offset(this.bb_pos, 60);
  return offset ? this.bb.readUint32(this.bb_pos + offset) : 0;
};

/**
 * @returns {number}
 */
pkNX.Structures.NestHoleDistributionEncounter8.prototype.Field1D = function() {
  var offset = this.bb.__offset(this.bb_pos, 62);
  return offset ? this.bb.readUint32(this.bb_pos + offset) : 0;
};

/**
 * @returns {number}
 */
pkNX.Structures.NestHoleDistributionEncounter8.prototype.Field1E = function() {
  var offset = this.bb.__offset(this.bb_pos, 64);
  return offset ? this.bb.readUint32(this.bb_pos + offset) : 0;
};

/**
 * @returns {number}
 */
pkNX.Structures.NestHoleDistributionEncounter8.prototype.Field1F = function() {
  var offset = this.bb.__offset(this.bb_pos, 66);
  return offset ? this.bb.readUint32(this.bb_pos + offset) : 0;
};

/**
 * @returns {number}
 */
pkNX.Structures.NestHoleDistributionEncounter8.prototype.Field20 = function() {
  var offset = this.bb.__offset(this.bb_pos, 68);
  return offset ? this.bb.readUint32(this.bb_pos + offset) : 0;
};

/**
 * @returns {number}
 */
pkNX.Structures.NestHoleDistributionEncounter8.prototype.Field21 = function() {
  var offset = this.bb.__offset(this.bb_pos, 70);
  return offset ? this.bb.readUint32(this.bb_pos + offset) : 0;
};

/**
 * @returns {number}
 */
pkNX.Structures.NestHoleDistributionEncounter8.prototype.Field22 = function() {
  var offset = this.bb.__offset(this.bb_pos, 72);
  return offset ? this.bb.readUint32(this.bb_pos + offset) : 0;
};

/**
 * @returns {number}
 */
pkNX.Structures.NestHoleDistributionEncounter8.prototype.Field23 = function() {
  var offset = this.bb.__offset(this.bb_pos, 74);
  return offset ? this.bb.readUint32(this.bb_pos + offset) : 0;
};

/**
 * @returns {number}
 */
pkNX.Structures.NestHoleDistributionEncounter8.prototype.Field24 = function() {
  var offset = this.bb.__offset(this.bb_pos, 76);
  return offset ? this.bb.readUint32(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Builder} builder
 */
pkNX.Structures.NestHoleDistributionEncounter8.startNestHoleDistributionEncounter8 = function(builder) {
  builder.startObject(37);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} EntryIndex
 */
pkNX.Structures.NestHoleDistributionEncounter8.addEntryIndex = function(builder, EntryIndex) {
  builder.addFieldInt32(0, EntryIndex, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} Species
 */
pkNX.Structures.NestHoleDistributionEncounter8.addSpecies = function(builder, Species) {
  builder.addFieldInt32(1, Species, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} AltForm
 */
pkNX.Structures.NestHoleDistributionEncounter8.addAltForm = function(builder, AltForm) {
  builder.addFieldInt32(2, AltForm, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} Level
 */
pkNX.Structures.NestHoleDistributionEncounter8.addLevel = function(builder, Level) {
  builder.addFieldInt32(3, Level, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} DynamaxLevel
 */
pkNX.Structures.NestHoleDistributionEncounter8.addDynamaxLevel = function(builder, DynamaxLevel) {
  builder.addFieldInt16(4, DynamaxLevel, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} Field05
 */
pkNX.Structures.NestHoleDistributionEncounter8.addField05 = function(builder, Field05) {
  builder.addFieldInt32(5, Field05, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} Field06
 */
pkNX.Structures.NestHoleDistributionEncounter8.addField06 = function(builder, Field06) {
  builder.addFieldInt32(6, Field06, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} Field07
 */
pkNX.Structures.NestHoleDistributionEncounter8.addField07 = function(builder, Field07) {
  builder.addFieldInt32(7, Field07, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} Field08
 */
pkNX.Structures.NestHoleDistributionEncounter8.addField08 = function(builder, Field08) {
  builder.addFieldInt32(8, Field08, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} Field09
 */
pkNX.Structures.NestHoleDistributionEncounter8.addField09 = function(builder, Field09) {
  builder.addFieldInt32(9, Field09, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} Field0A
 */
pkNX.Structures.NestHoleDistributionEncounter8.addField0A = function(builder, Field0A) {
  builder.addFieldInt32(10, Field0A, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} Ability
 */
pkNX.Structures.NestHoleDistributionEncounter8.addAbility = function(builder, Ability) {
  builder.addFieldInt8(11, Ability, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {boolean} IsGigantamax
 */
pkNX.Structures.NestHoleDistributionEncounter8.addIsGigantamax = function(builder, IsGigantamax) {
  builder.addFieldInt8(12, +IsGigantamax, +false);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Long} DropTableID
 */
pkNX.Structures.NestHoleDistributionEncounter8.addDropTableID = function(builder, DropTableID) {
  builder.addFieldInt64(13, DropTableID, builder.createLong(0, 0));
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Long} BonusTableID
 */
pkNX.Structures.NestHoleDistributionEncounter8.addBonusTableID = function(builder, BonusTableID) {
  builder.addFieldInt64(14, BonusTableID, builder.createLong(0, 0));
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} ProbabilitiesOffset
 */
pkNX.Structures.NestHoleDistributionEncounter8.addProbabilities = function(builder, ProbabilitiesOffset) {
  builder.addFieldOffset(15, ProbabilitiesOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {Array.<number>} data
 * @returns {flatbuffers.Offset}
 */
pkNX.Structures.NestHoleDistributionEncounter8.createProbabilitiesVector = function(builder, data) {
  builder.startVector(4, data.length, 4);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addInt32(data[i]);
  }
  return builder.endVector();
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
pkNX.Structures.NestHoleDistributionEncounter8.startProbabilitiesVector = function(builder, numElems) {
  builder.startVector(4, numElems, 4);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} Gender
 */
pkNX.Structures.NestHoleDistributionEncounter8.addGender = function(builder, Gender) {
  builder.addFieldInt8(16, Gender, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} FlawlessIVs
 */
pkNX.Structures.NestHoleDistributionEncounter8.addFlawlessIVs = function(builder, FlawlessIVs) {
  builder.addFieldInt8(17, FlawlessIVs, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} Field12
 */
pkNX.Structures.NestHoleDistributionEncounter8.addField12 = function(builder, Field12) {
  builder.addFieldInt8(18, Field12, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} Field13
 */
pkNX.Structures.NestHoleDistributionEncounter8.addField13 = function(builder, Field13) {
  builder.addFieldInt8(19, Field13, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} Field14
 */
pkNX.Structures.NestHoleDistributionEncounter8.addField14 = function(builder, Field14) {
  builder.addFieldInt8(20, Field14, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} Nature
 */
pkNX.Structures.NestHoleDistributionEncounter8.addNature = function(builder, Nature) {
  builder.addFieldInt8(21, Nature, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} Field16
 */
pkNX.Structures.NestHoleDistributionEncounter8.addField16 = function(builder, Field16) {
  builder.addFieldInt32(22, Field16, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} Move0
 */
pkNX.Structures.NestHoleDistributionEncounter8.addMove0 = function(builder, Move0) {
  builder.addFieldInt32(23, Move0, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} Move1
 */
pkNX.Structures.NestHoleDistributionEncounter8.addMove1 = function(builder, Move1) {
  builder.addFieldInt32(24, Move1, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} Move2
 */
pkNX.Structures.NestHoleDistributionEncounter8.addMove2 = function(builder, Move2) {
  builder.addFieldInt32(25, Move2, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} Move3
 */
pkNX.Structures.NestHoleDistributionEncounter8.addMove3 = function(builder, Move3) {
  builder.addFieldInt32(26, Move3, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} DynamaxBoost
 */
pkNX.Structures.NestHoleDistributionEncounter8.addDynamaxBoost = function(builder, DynamaxBoost) {
  builder.addFieldFloat32(27, DynamaxBoost, 0.0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} Field1C
 */
pkNX.Structures.NestHoleDistributionEncounter8.addField1C = function(builder, Field1C) {
  builder.addFieldInt32(28, Field1C, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} Field1D
 */
pkNX.Structures.NestHoleDistributionEncounter8.addField1D = function(builder, Field1D) {
  builder.addFieldInt32(29, Field1D, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} Field1E
 */
pkNX.Structures.NestHoleDistributionEncounter8.addField1E = function(builder, Field1E) {
  builder.addFieldInt32(30, Field1E, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} Field1F
 */
pkNX.Structures.NestHoleDistributionEncounter8.addField1F = function(builder, Field1F) {
  builder.addFieldInt32(31, Field1F, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} Field20
 */
pkNX.Structures.NestHoleDistributionEncounter8.addField20 = function(builder, Field20) {
  builder.addFieldInt32(32, Field20, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} Field21
 */
pkNX.Structures.NestHoleDistributionEncounter8.addField21 = function(builder, Field21) {
  builder.addFieldInt32(33, Field21, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} Field22
 */
pkNX.Structures.NestHoleDistributionEncounter8.addField22 = function(builder, Field22) {
  builder.addFieldInt32(34, Field22, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} Field23
 */
pkNX.Structures.NestHoleDistributionEncounter8.addField23 = function(builder, Field23) {
  builder.addFieldInt32(35, Field23, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} Field24
 */
pkNX.Structures.NestHoleDistributionEncounter8.addField24 = function(builder, Field24) {
  builder.addFieldInt32(36, Field24, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
pkNX.Structures.NestHoleDistributionEncounter8.endNestHoleDistributionEncounter8 = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} EntryIndex
 * @param {number} Species
 * @param {number} AltForm
 * @param {number} Level
 * @param {number} DynamaxLevel
 * @param {number} Field05
 * @param {number} Field06
 * @param {number} Field07
 * @param {number} Field08
 * @param {number} Field09
 * @param {number} Field0A
 * @param {number} Ability
 * @param {boolean} IsGigantamax
 * @param {flatbuffers.Long} DropTableID
 * @param {flatbuffers.Long} BonusTableID
 * @param {flatbuffers.Offset} ProbabilitiesOffset
 * @param {number} Gender
 * @param {number} FlawlessIVs
 * @param {number} Field12
 * @param {number} Field13
 * @param {number} Field14
 * @param {number} Nature
 * @param {number} Field16
 * @param {number} Move0
 * @param {number} Move1
 * @param {number} Move2
 * @param {number} Move3
 * @param {number} DynamaxBoost
 * @param {number} Field1C
 * @param {number} Field1D
 * @param {number} Field1E
 * @param {number} Field1F
 * @param {number} Field20
 * @param {number} Field21
 * @param {number} Field22
 * @param {number} Field23
 * @param {number} Field24
 * @returns {flatbuffers.Offset}
 */
pkNX.Structures.NestHoleDistributionEncounter8.createNestHoleDistributionEncounter8 = function(builder, EntryIndex, Species, AltForm, Level, DynamaxLevel, Field05, Field06, Field07, Field08, Field09, Field0A, Ability, IsGigantamax, DropTableID, BonusTableID, ProbabilitiesOffset, Gender, FlawlessIVs, Field12, Field13, Field14, Nature, Field16, Move0, Move1, Move2, Move3, DynamaxBoost, Field1C, Field1D, Field1E, Field1F, Field20, Field21, Field22, Field23, Field24) {
  pkNX.Structures.NestHoleDistributionEncounter8.startNestHoleDistributionEncounter8(builder);
  pkNX.Structures.NestHoleDistributionEncounter8.addEntryIndex(builder, EntryIndex);
  pkNX.Structures.NestHoleDistributionEncounter8.addSpecies(builder, Species);
  pkNX.Structures.NestHoleDistributionEncounter8.addAltForm(builder, AltForm);
  pkNX.Structures.NestHoleDistributionEncounter8.addLevel(builder, Level);
  pkNX.Structures.NestHoleDistributionEncounter8.addDynamaxLevel(builder, DynamaxLevel);
  pkNX.Structures.NestHoleDistributionEncounter8.addField05(builder, Field05);
  pkNX.Structures.NestHoleDistributionEncounter8.addField06(builder, Field06);
  pkNX.Structures.NestHoleDistributionEncounter8.addField07(builder, Field07);
  pkNX.Structures.NestHoleDistributionEncounter8.addField08(builder, Field08);
  pkNX.Structures.NestHoleDistributionEncounter8.addField09(builder, Field09);
  pkNX.Structures.NestHoleDistributionEncounter8.addField0A(builder, Field0A);
  pkNX.Structures.NestHoleDistributionEncounter8.addAbility(builder, Ability);
  pkNX.Structures.NestHoleDistributionEncounter8.addIsGigantamax(builder, IsGigantamax);
  pkNX.Structures.NestHoleDistributionEncounter8.addDropTableID(builder, DropTableID);
  pkNX.Structures.NestHoleDistributionEncounter8.addBonusTableID(builder, BonusTableID);
  pkNX.Structures.NestHoleDistributionEncounter8.addProbabilities(builder, ProbabilitiesOffset);
  pkNX.Structures.NestHoleDistributionEncounter8.addGender(builder, Gender);
  pkNX.Structures.NestHoleDistributionEncounter8.addFlawlessIVs(builder, FlawlessIVs);
  pkNX.Structures.NestHoleDistributionEncounter8.addField12(builder, Field12);
  pkNX.Structures.NestHoleDistributionEncounter8.addField13(builder, Field13);
  pkNX.Structures.NestHoleDistributionEncounter8.addField14(builder, Field14);
  pkNX.Structures.NestHoleDistributionEncounter8.addNature(builder, Nature);
  pkNX.Structures.NestHoleDistributionEncounter8.addField16(builder, Field16);
  pkNX.Structures.NestHoleDistributionEncounter8.addMove0(builder, Move0);
  pkNX.Structures.NestHoleDistributionEncounter8.addMove1(builder, Move1);
  pkNX.Structures.NestHoleDistributionEncounter8.addMove2(builder, Move2);
  pkNX.Structures.NestHoleDistributionEncounter8.addMove3(builder, Move3);
  pkNX.Structures.NestHoleDistributionEncounter8.addDynamaxBoost(builder, DynamaxBoost);
  pkNX.Structures.NestHoleDistributionEncounter8.addField1C(builder, Field1C);
  pkNX.Structures.NestHoleDistributionEncounter8.addField1D(builder, Field1D);
  pkNX.Structures.NestHoleDistributionEncounter8.addField1E(builder, Field1E);
  pkNX.Structures.NestHoleDistributionEncounter8.addField1F(builder, Field1F);
  pkNX.Structures.NestHoleDistributionEncounter8.addField20(builder, Field20);
  pkNX.Structures.NestHoleDistributionEncounter8.addField21(builder, Field21);
  pkNX.Structures.NestHoleDistributionEncounter8.addField22(builder, Field22);
  pkNX.Structures.NestHoleDistributionEncounter8.addField23(builder, Field23);
  pkNX.Structures.NestHoleDistributionEncounter8.addField24(builder, Field24);
  return pkNX.Structures.NestHoleDistributionEncounter8.endNestHoleDistributionEncounter8(builder);
}

// Exports for Node.js and RequireJS
this.pkNX = pkNX;
